//더미 데이터 입니다~ 나중에 서버에서 받아오면 될 듯요 잘 수정해봐요
let reviewDummyData = [
  {
    title: "제목1",
    review: "리뷰1",
    place: "장소1",
    doneDate: "2021-08-01",
    expression: "좋아요",
    todoId: 1,
    file: "https://via.placeholder.com/600",
  },
  {
    title: "제목2",
    review: "리뷰2",
    place: "장소2",
    doneDate: "2021-08-02",
    expression: "좋아요",
    todoId: 2,
    file: "https://via.placeholder.com/600",
  },
  {
    title: "제목3",
    review: "리뷰3",
    place: "장소3",
    doneDate: "2021-08-03",
    expression: "좋아요",
    todoId: 3,
    file: "https://via.placeholder.com/600",
  },
  {
    title: "제목4",
    review: "리뷰4",
    place: "장소4",
    doneDate: "2021-08-04",
    expression: "좋아요",
    todoId: 4,
    file: "https://via.placeholder.com/600",
  },
  {
    title: "제목5",
    review: "리뷰5",
    place: "장소5",
    doneDate: "2021-08-05",
    expression: "좋아요",
    todoId: 5,
    file: "https://via.placeholder.com/600",
  },
  {
    title: "제목6",
    review: "리뷰6",
    place: "장소6",
    doneDate: "2021-08-06",
    expression: "좋아요",
    todoId: 6,
    file: "https://via.placeholder.com/600",
  },
  {
    title: "제목7",
    review: "리뷰7",
    place: "장소7",
    doneDate: "2021-08-07",
    expression: "좋아요",
    todoId: 7,
    file: "https://via.placeholder.com/600",
  },
  {
    title: "제목8",
    review: "리뷰8",
    place: "장소8",
    doneDate: "2021-08-08",
    expression: "좋아요",
    todoId: 8,
    file: "https://via.placeholder.com/600",
  },
  {
    title: "제목9",
    review: "리뷰9",
    place: "장소9",
    doneDate: "2021-08-09",
    expression: "좋아요",
    todoId: 9,
    file: "https://via.placeholder.com/600",
  },
  {
    title: "제목10",
    review: "리뷰10",
    place: "장소10",
    doneDate: "2021-08-10",
    expression: "좋아요",
    todoId: 10,
    file: "https://via.placeholder.com/600",
  },
];

export default reviewDummyData;
