DROP TABLE todo IF EXISTS;
CREATE TABLE todo (
    id bigint generated by default as identity,
    user varchar(255),
    name varchar(255),
    date varchar(255),
    category varchar(255),
    content varchar(255),
    state boolean default false,
    review_id bigint,
    primary key (id)
);

DROP TABLE upload_file IF EXISTS;
CREATE TABLE upload_file (
    id bigint generated by default as identity,
    original_file_name varchar(255),
    full_path varchar(255),
    primary key (id)
);

DROP TABLE review IF EXISTS;
CREATE TABLE review (
    id bigint generated by default as identity,
    title varchar(255),
    review varchar(255),
    done_date varchar(255),
    place varchar(255),
    expression varchar(255),
    photo_id bigint,
    primary key (id)
);